{{if and (eq .Values.global.hpa.enabled "on") (eq .Values.global.resources.enabled "on") }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "eric-udm-udmprovisioningvalidator.deploy.name" . }}
{{- include "eric-udm-udmprovisioningvalidator.helm-labels" . | indent 2 }}
{{- include "eric-udm-udmprovisioningvalidator.helm-annotations" . | indent 2 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.service.name }}
  minReplicas: {{ .Values.hpa.replicas.min }}
  maxReplicas: {{ .Values.hpa.replicas.max }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.target.cpu }}
{{end}}
